CREATE TABLE ANIMAL(
ID NUMBER NOT NULL PRIMARY KEY,
NOME VARCHAR2(100) NOT NULL,
SEXO VARCHAR(1) NOT NULL,
VALOR NUMBER(10,2) NOT NULL
);
CREATE SEQUENCE ANIMAL_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE TABLE CLIENTE(
ID NUMBER NOT NULL PRIMARY KEY,
NOME VARCHAR2(100) NOT NULL,
SEXO VARCHAR(1) NOT NULL,
PROFISSAO VARCHAR2(100) NOT NULL
);
CREATE SEQUENCE CLIENTE_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 alter table ANIMAL add ID_CLIENTE number not null; 
 alter table ANIMAL add foreign key (ID_CLIENTE) references CLIENTE(id);
 commit;
 
 select * from CLIENTE;