CREATE TABLE PAIS(
    ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    SIGLA  VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE PAIS_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE TABLE ESTADO(
    ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    ID_PAIS NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    SIGLA  VARCHAR2(100) NOT NULL,
    FOREIGN KEY (ID_PAIS)
        REFERENCES PAIS(ID)
        ON DELETE CASCADE
);
CREATE SEQUENCE ESTADO_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 CREATE TABLE CIDADE(
    ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    ID_ESTADO NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    SIGLA  VARCHAR2(100) NOT NULL,
    FOREIGN KEY (ID_ESTADO)
        REFERENCES ESTADO(ID)
        ON DELETE CASCADE
);
CREATE SEQUENCE CIDADE_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
INSERT INTO PAIS
 VALUES(
    PAIS_SEQ.NEXTVAL,
    'BRASIL',
    'BR'
 );
 
INSERT INTO ESTADO
 VALUES(
    ESTADO_SEQ.NEXTVAL,
    1,
    'RIO GRANDE DO SUL',
    'RS'
 );
 
 INSERT INTO CIDADE
 VALUES(
    CIDADE_SEQ.NEXTVAL,
    1,
    'SANTA MARIA',
    'SM'
 );
 
SELECT * FROM CIDADE C 
 INNER JOIN ESTADO E ON E.ID = C.ID_ESTADO
 INNER JOIN PAIS P ON P.ID = E.ID_PAIS;
 
COMMIT;
/*
DROP TABLE PAIS;
DROP SEQUENCE PAIS_SEQ;
DROP TABLE ESTADO;
DROP SEQUENCE ESTADO_SEQ;
DROP TABLE CIDADE;
DROP SEQUENCE CIDADE_SEQ;
SELECT * FROM PAIS;
SELECT * FROM ESTADO;
SELECT * FROM CIDADE;
*/
