/*DDL*/
CREATE TABLE USUARIO(
    ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    NASCIMENTO DATE
);
CREATE SEQUENCE USUARIO_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
CREATE TABLE SISTEMA(
    ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL
);
CREATE SEQUENCE SISTEMA_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
CREATE TABLE USUARIO_SISTEMA(
    ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    ID_USUARIO NUMBER NOT NULL,
    ID_SISTEMA NUMBER NOT NULL,
    FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO(ID)
        ON DELETE CASCADE,
    FOREIGN KEY (ID_SISTEMA)
        REFERENCES SISTEMA(ID)
        ON DELETE CASCADE
);
CREATE SEQUENCE USUARIO_SISTEMA_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
  /*DataTypes*/
  CREATE TABLE EXAMPLE_DATA_TYPES(
    ID NUMBER(38,0),
    INTEIRO INTEGER,
    NOME VARCHAR2(100),
    DATAS DATE,
    DATA_HORA TIMESTAMP,
    TEXTAO CLOB
  );
  
 
 /*DML*/
 INSERT INTO USUARIO 
 VALUES(
    USUARIO_SEQ.NEXTVAL,
    'JACINTO',
    TO_DATE('10/10/1900', 'DD/MM/YYYY')
 );
  INSERT INTO SISTEMA(ID, NOME) 
  VALUES(
    SISTEMA_SEQ.NEXTVAL,
    'WORD'
 );
 INSERT INTO USUARIO_SISTEMA(ID, ID_SISTEMA, ID_USUARIO) 
 VALUES(
    USUARIO_SISTEMA_SEQ.NEXTVAL,
    1,
    1
 );
 INSERT INTO USUARIO_SISTEMA(ID, ID_SISTEMA, ID_USUARIO) 
 VALUES(
    USUARIO_SISTEMA_SEQ.NEXTVAL,
    1,
    2
 );
 SELECT * FROM USUARIO_SISTEMA US 
 INNER JOIN USUARIO U ON U.ID = US.ID_USUARIO
 INNER JOIN SISTEMA S ON S.ID = US.ID_SISTEMA;
 
 SELECT TO_TIMESTAMP('10/10/1900 23:09:59', 'DD/MM/YYYY HH24:MI:SS') FROM DUAL;
 
 INSERT INTO EXAMPLE_DATA_TYPES(DATA_HORA, TEXTAO) 
 VALUES(
  TO_TIMESTAMP('10/10/1900 23:09:59', 'DD/MM/YYYY HH24:MI:SS'),
  TO_CLOB('TEXTAO')
 );
 
 SELECT * FROM EXAMPLE_DATA_TYPES;
 
 TRUNCATE TABLE EXAMPLE_DATA_TYPES;
 
 DROP TABLE EXAMPLE_DATA_TYPES;
 
 ALTER TABLE SISTEMA ADD SISTEMA_PAI NUMBER;
 
 ALTER TABLE SISTEMA ADD FOREIGN KEY (SISTEMA_PAI) REFERENCES SISTEMA(ID) ON DELETE CASCADE;
 
 SELECT * FROM SISTEMA;
 
 INSERT INTO SISTEMA
  VALUES(
    SISTEMA_SEQ.NEXTVAL,
    'WINDOWS'
 );
  
 SELECT * FROM USUARIO_SISTEMA US 
 INNER JOIN USUARIO U ON U.ID = US.ID_USUARIO
 INNER JOIN SISTEMA S ON S.ID = US.ID_SISTEMA
 LEFT JOIN SISTEMA PAI ON PAI.ID = S.SISTEMA_PAI;
 
 UPDATE SISTEMA SET SISTEMA_PAI = 2 WHERE ID=1;
 
 DELETE FROM SISTEMA WHERE ID = 2;
 
 ROLLBACK;
 COMMIT;
 
 

