-- CRIAR TABELA CLIENTE
CREATE TABLE CLIENTE(
    ID INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(100)
);
CREATE SEQUENCE CLIENTE_SEQ;

-- CRIAR TABELA FILME
CREATE TABLE FILME(
    ID INTEGER NOT NULL PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    LANCAMENTO DATE,
    CATEGORIA VARCHAR(100)
);
CREATE SEQUENCE FILME_SEQ;

-- CRIAR TABELA ALUGUEL
CREATE TABLE ALUGUEL(
    ID INTEGER NOT NULL PRIMARY KEY,
    RETIRADA DATE NOT NULL,
    PREVISAO DATE NOT NULL,
    DEVOLUCAO DATE,
    MULTA FLOAT,
    ID_CLIENTE INTEGER NOT NULL REFERENCES CLIENTE(ID)
);
CREATE SEQUENCE ALUGUEL_SEQ;

-- CRIAR TABELA MIDIA
CREATE TABLE MIDIA(
    ID INTEGER NOT NULL PRIMARY KEY,
    TIPO VARCHAR(100) NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    ID_FILME INTEGER NOT NULL REFERENCES FILME(ID)
    ID_ALUGUEL INTEGER REFERENCES ALUGUEL(ID)
);
CREATE SEQUENCE MIDIA_SEQ;

-- CRIAR TABELA VALOR_MIDIA
CREATE TABLE VALOR_MIDIA(
    ID INTEGER NOT NULL PRIMARY KEY,
    VALOR FLOAT NOT NULL,
    INICIO_VIGENCIA DATE NOT NULL,
    FINAL_VIGENCIA DATE,
    ID_MIDIA INTEGER NOT NULL REFERENCES MIDIA(ID)
);
CREATE SEQUENCE VALOR_MIDIA_SEQ;

COMMIT;

DROP TABLE CLIENTE;
DROP SEQUENCE CLIENTE_SEQ;
DROP TABLE FILME;
DROP SEQUENCE FILME_SEQ;
DROP TABLE ALUGUEL;
DROP SEQUENCE ALUGUEL_SEQ;
DROP TABLE MIDIA;
DROP SEQUENCE MIDIA_SEQ;
DROP TABLE VALOR_MIDIA;
DROP SEQUENCE VALOR_MIDIA_SEQ;

